Current configuration:
!
frr version 10.5.1
frr defaults traditional
hostname pfsense-lab.IndonesiaCentral.cloudapp.azure.com
service integrated-vtysh-config
!
ip route 10.126.64.0/18 hn1
ip route 10.151.64.84/32 hn0
ip route 169.254.100.2/32 gre0
!
router bgp 64512
 bgp router-id 10.126.64.4
 no bgp ebgp-requires-policy
 neighbor 169.254.100.2 remote-as 64513
 neighbor 169.254.100.2 description CHR-Alibaba-ap-southeast-5
 !
 address-family ipv4 unicast
  network 10.126.64.0/18
  network 10.126.64.0/26
  network 10.126.65.0/24
  neighbor 169.254.100.2 soft-reconfiguration inbound
 exit-address-family
exit
!
end
